create table if not exists courses (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  category text default 'General',
  created_at timestamptz default now()
);

alter table courses enable row level security;

create policy "Anyone can read courses"
on courses for select using (true);

create policy "Authenticated users can insert courses"
on courses for insert to authenticated with check (true);

create policy "Authenticated users can delete courses"
on courses for delete to authenticated using (true);

insert into courses (title,description,category) values
('Data Analysis','تعلم Excel وSQL وPower BI لتحليل البيانات','Data'),
('Business Analysis','تعلم تحليل متطلبات الأعمال والعمليات','Business'),
('Database Fundamentals','أساسيات قواعد البيانات وSQL','Database')
on conflict do nothing;
